[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
description = "Generator of Rust code as interface between SimplicityHL and Rust."
publish = false

[package.metadata.rbmt.lint]
# Bitcoin/Elements use different hash and hex majors, serde/wasm use different syn majors.
allowed_duplicates = ["bitcoin_hashes", "hex-conservative", "syn"]

[dependencies]
simplicityhl = { path = ".." , features = ["docs"]}

serde = { version = "1.0.188", features = ["derive"]}
serde_json = { version = "1.0.105"}
clap = "4.5.37"
