name: Publish VS Code Extension

on:
    push:
        branches:
            - master
        paths:
            - "vscode/**"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Install dependencies and build
              working-directory: ./vscode
              run: |
                  npm install
                  npm run compile

            - name: Publish to VS Code Marketplace
              working-directory: ./vscode
              run: npx vsce publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
